# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Add NDFC Fabric Devices {{ MD.vxlan.global.name }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ MD.vxlan.global.name }}"
    config: "{{ updated_inv_config['updated_inv_list'] }}"
    deploy: false
    save: true
    state: merged
  vars:
      ansible_command_timeout: 3600
      ansible_connect_timeout: 3600
  when: MD_Extended.vxlan.topology.switches | length > 0

- name: Default Policy Payload Variable
  ansible.builtin.set_fact:
    policy_payload: []
  delegate_to: localhost

- name: Build Switch Hostname Policy Payload from Data Model Update
  cisco.nac_dc_vxlan.dtc.build_hostname_policy_payload:
    model_data: "{{ MD.vxlan.topology.switches }}"
    domain: local
    userName: "{{ ansible_user }}"
    userPasswd: "{{ ansible_password }}"
    nd: "{{ ansible_host }}"
  register: results
  delegate_to: localhost

- name: Set Policy Payload
  ansible.builtin.set_fact:
    policy_payload: "{{ results['policy_payload'] }}"
  delegate_to: localhost

- name: Display Policy Payload
  ansible.builtin.debug:
    msg: "{{ policy_payload }}"

- name: Set Policy_ids
  ansible.builtin.set_fact:
    policy_ids: "{{ results['policy_ids'] }}"
  delegate_to: localhost

- name: Display Policy ids
  ansible.builtin.debug:
    msg: "{{ policy_ids }}"

- name: Update Switch Hostname Policy in NDFC
  cisco.dcnm.dcnm_rest:
    method: PUT
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/policies/{{ policy_ids }}/bulk"
    json_data: "{{ policy_payload | to_json }}"
  when: policy_payload | length > 0
